[package]
edition = "2021"
name = "yew-gettingstart"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# this is the development version of Yew
yew = {git = "https://github.com/yewstack/yew/", features = ["csr"]}
